args<-commandArgs(trailingOnly=TRUE)

library(RColorBrewer)


n50<-function(x){
	y<-x[order(x, decreasing=T)]
	
	return(y[which(cumsum(as.numeric(y)) >= (sum(as.numeric(y))/2))[1]])
}


BASE<-args[1]	# This has to be the path to the "stats" folder generated by the 'SEQUELstats.sh' script!
SPEC<-args[2]	# Sample name e.g. "fErpCal1"


setwd(BASE)

statSets<-c("Hn","HpSn","HpSp")
statNames<-c("LQ","MQ","HQ")
statCols<-c("ZR","PR","SR")
statRows<-c("COUNT","SEQ","MEAN","MEDIAN","N50","PSR","ZOR")
statFrame<-as.data.frame(matrix(rep(0,length(statRows)*length(statCols)), ncol=length(statCols)))
rownames(statFrame)<-statRows
colnames(statFrame)<-statCols


PacBio.stats<-NULL
PacBio.hists<-NULL
PacBio.other<-NULL


#- Parse data produced by "SEQUEL_stats.pl"
for (h in 1:length(statSets)) {
	setwd(paste(BASE, "/", statSets[h], sep=""))
	
	for (i in list.files(patt=".stats")) {
		tmpFrame<-read.table(i, header=F, sep="\t", stringsAsFactors=F)
		tmpCell<-tmpFrame[1,1]
		
		if(!(tmpCell %in% names(PacBio.stats))) { PacBio.stats[[tmpCell]]<-NULL }
		
		PacBio.stats[[tmpCell]][[statNames[h]]]<-statFrame
		
		for (j in 1:nrow(tmpFrame)) {
			PacBio.stats[[tmpCell]][[statNames[h]]][tmpFrame[j,3],tmpFrame[j,2]]<-tmpFrame[j,4]
		}
	}
	
	if(statSets[h] == "HpSp") {
		for (i in list.files(patt=".hist")) {
			tmpFrame<-read.table(i, header=F, sep="\t", stringsAsFactors=F)
			tmpCell<-tmpFrame[1,1]
			
			if(!(tmpCell %in% names(PacBio.hists))) { PacBio.hists[[tmpCell]]<-NULL }
			
			PacBio.hists[[tmpCell]][[statNames[h]]]<-tmpFrame[,2:4]
			colnames(PacBio.hists[[tmpCell]][[statNames[h]]])<-c("BIN","PR","SR")
		}
		
		for (i in list.files(patt=".aCnt")) {
			tmpFrame<-read.table(i, header=F, sep="\t", stringsAsFactors=F)
			tmpCell<-tmpFrame[1,1]
			
			if(!(tmpCell %in% names(PacBio.other))) { PacBio.other[[tmpCell]]<-NULL }
			if(!(statNames[h] %in% names(PacBio.other[[tmpCell]]))) { PacBio.other[[tmpCell]][[statNames[h]]]<-NULL }
			
			PacBio.other[[tmpCell]][[statNames[h]]][["aCnt"]]<-as.vector(tmpFrame[,2])
		}
		
		for (i in list.files(patt=".lFlg")) {
			tmpFrame<-read.table(i, header=F, sep="\t", stringsAsFactors=F)
			tmpCell<-tmpFrame[1,1]
			
			if(!(tmpCell %in% names(PacBio.other))) { PacBio.other[[tmpCell]]<-NULL }
			if(!(statNames[h] %in% names(PacBio.other[[tmpCell]]))) { PacBio.other[[tmpCell]][[statNames[h]]]<-NULL }
			
			PacBio.other[[tmpCell]][[statNames[h]]][["lFlg"]]<-as.vector(tmpFrame[,2])
		}
	}
}
#-


PacBio.max<-matrix(rep(0,(2*length(names(PacBio.hists)))), ncol=2)
rownames(PacBio.max)<-names(PacBio.hists)
colnames(PacBio.max)<-c("LEN","CNT")

for (i in names(PacBio.hists)) {
	PacBio.max[i,"LEN"]<-PacBio.hists[[i]][["HQ"]][rev(which(PacBio.hists[[i]][["HQ"]][,"PR"] != 0))[1],"BIN"]
	PacBio.max[i,"CNT"]<-max(c(max(PacBio.hists[[i]][["HQ"]][,"PR"], na.rm=T), max(PacBio.hists[[i]][["HQ"]][,"SR"], na.rm=T)), na.rm=T)
}



SMRTcells<-names(PacBio.stats)

PReadStats<-data.frame("SEQ"=rep(0,length(SMRTcells)), "Median"=rep(0,length(SMRTcells)), "Mean"=rep(0,length(SMRTcells)), "N50"=rep(0,length(SMRTcells)), "ZOR"=rep(0,length(SMRTcells)), "PSR"=rep(0,length(SMRTcells)))
SReadStats<-data.frame("SEQ"=rep(0,length(SMRTcells)), "Median"=rep(0,length(SMRTcells)), "Mean"=rep(0,length(SMRTcells)), "N50"=rep(0,length(SMRTcells)))
rownames(PReadStats)<-SMRTcells
rownames(SReadStats)<-SMRTcells

for (i in SMRTcells) {
	PReadStats[i,"ZOR"]<-PacBio.stats[[i]][["HQ"]]["ZOR","PR"]
	PReadStats[i,"PSR"]<-PacBio.stats[[i]][["HQ"]]["PSR","PR"]
	
	PReadStats[i,"SEQ"]<-PacBio.stats[[i]][["HQ"]]["SEQ","PR"]
	PReadStats[i,"Mean"]<-PacBio.stats[[i]][["HQ"]]["MEAN","PR"]
	PReadStats[i,"Median"]<-PacBio.stats[[i]][["HQ"]]["MEDIAN","PR"]
	PReadStats[i,"N50"]<-PacBio.stats[[i]][["HQ"]]["N50","PR"]
	
	SReadStats[i,"SEQ"]<-PacBio.stats[[i]][["HQ"]]["SEQ","SR"]
	SReadStats[i,"Mean"]<-PacBio.stats[[i]][["HQ"]]["MEAN","SR"]
	SReadStats[i,"Median"]<-PacBio.stats[[i]][["HQ"]]["MEDIAN","SR"]
	SReadStats[i,"N50"]<-PacBio.stats[[i]][["HQ"]]["N50","SR"]
}



setwd(BASE)



#-	1)	Polymerase read & Subread length profiles
ppRow<-300
ppCol<-480

pRows<-ceiling((length(SMRTcells)*2)/4)
pCols<-length(SMRTcells)

if(pCols>4) { pCols<-4 }

maxRLength<-60000	#ceiling(max(PacBio.max[,"LEN"]) / 10000) * 10000
maxRCount<-ceiling(max(PacBio.max[,"CNT"]) / 1000) * 1000


png(paste(SPEC, "Polymerase_and_subread.length_profiles.png", sep="."), width=(pCols*ppCol), height=(pRows*ppRow))

par(mfrow=c(pRows,pCols))

for (i in SMRTcells) {
	plot(PacBio.hists[[i]][["HQ"]][,c("BIN","PR")], type="h", col="red4", xlim=c(-100,maxRLength), ylim=c(0,maxRCount), xlab="Polymerase read length", ylab="Count", main=i, bty="n")
	lines(c(PacBio.stats[[i]][["HQ"]]["MEAN","PR"],PacBio.stats[[i]][["HQ"]]["MEAN","PR"]),c(0,maxRCount), lwd=1, lty=2, col="black")
	lines(c(PacBio.stats[[i]][["HQ"]]["MEDIAN","PR"],PacBio.stats[[i]][["HQ"]]["MEDIAN","PR"]),c(0,maxRCount), lwd=1, lty=3, col="black")
	lines(c(PacBio.stats[[i]][["HQ"]]["N50","PR"],PacBio.stats[[i]][["HQ"]]["N50","PR"]),c(0,maxRCount), lwd=1, lty=4, col="black")
	
	plot(PacBio.hists[[i]][["HQ"]][,c("BIN","SR")], type="h", col="green4", xlim=c(-100,maxRLength), ylim=c(0,maxRCount), xlab="Subread length", ylab="Count", main=i, bty="n")
	lines(c(PacBio.stats[[i]][["HQ"]]["MEAN","SR"],PacBio.stats[[i]][["HQ"]]["MEAN","SR"]),c(0,maxRCount), lwd=1, lty=2, col="black")
	lines(c(PacBio.stats[[i]][["HQ"]]["MEDIAN","SR"],PacBio.stats[[i]][["HQ"]]["MEDIAN","SR"]),c(0,maxRCount), lwd=1, lty=3, col="black")
	lines(c(PacBio.stats[[i]][["HQ"]]["N50","SR"],PacBio.stats[[i]][["HQ"]]["N50","SR"]),c(0,maxRCount), lwd=1, lty=4, col="black")
}

dev.off()
#-



#-	2)	SMRT cell raw output plot
ppRow<-800
ppCol<-800

pRows<-1
pCols<-1

covCols<-c(colorRampPalette(brewer.pal(8,"RdYlGn")[1:4])(10),colorRampPalette(brewer.pal(8,"RdYlGn")[5:8])(10))

xLim<-40
yLim<-10
stp<-20
xScf<-1000
yScf<-1000000000


png(paste(SPEC, "SMRT_cell.raw_output.png", sep="."), width=(pCols*ppCol), height=(pRows*ppRow))

plot(NULL, xlim=c(0,xLim), ylim=c(0,yLim), xlab="", ylab="", xaxt="n", yaxt="n", bty="n", main="SMRT cell raw output analysis")

for (i in 1:stp) {
	tCol<-col2rgb(covCols[i])
	xf<-xLim/stp
	rect(((i-1)*xf), 0, (i*xf), yLim, col=rgb(tCol[1], tCol[2], tCol[3], 128, maxColorValue=255), border=NA)
}

for (i in 1:stp) {
	tCol<-col2rgb(covCols[i])
	yf<-yLim/stp
	rect(0, ((i-1)*yf), xLim, (i*yf), col=rgb(tCol[1], tCol[2], tCol[3], 128, maxColorValue=255), border=NA)
}


for (i in 11:stp) {
	tCol<-col2rgb(covCols[i])
	xf<-xLim/stp
	yf<-yLim/stp
	rect(((i-1)*xf), (10*yf), (i*xf), (16*yf), col=rgb(tCol[1], tCol[2], tCol[3], 128, maxColorValue=255), border=NA)
}

for (i in 11:16) {
	tCol<-col2rgb(covCols[i])
	xf<-xLim/stp
	yf<-yLim/stp
	rect((10*xf), ((i-1)*yf), xLim, (i*yf), col=rgb(tCol[1], tCol[2], tCol[3], 128, maxColorValue=255), border=NA)
}


for (i in 0:stp) {
	xf<-xLim/stp
	yf<-yLim/stp
	
	lines(c(0,xLim), c((i*yf),(i*yf)), col="black", lwd=1, lty=3)
	lines(c((i*xf),(i*xf)), c(0,yLim), col="black", lwd=1, lty=3)
}

lines(c(0,xLim), c((yLim/2),(yLim/2)), col="black", lwd=1, lty=1)
lines(c((xLim/2),(xLim/2)), c(0,yLim), col="black", lwd=1, lty=1)

rect((xLim/2), (yLim/2), xLim, ((yLim/stp)*16), col=NA, border="black", lwd=1, lty=1)


for (i in SMRTcells) {
	tY<-(PReadStats[i,"SEQ"]/yScf)
	tXl<-(PReadStats[i,"Median"]/xScf)
	tXr<-(PReadStats[i,"N50"]/xScf)
	
	lines(c(tXl,tXr), c(tY,tY), col="black", lwd=1, lty=1)
}

par(new=T)
plot((PReadStats[,"N50"]/xScf), (PReadStats[,"SEQ"]/yScf), pch=21, col="black", bg="white", lwd=2, cex=2.0, xlim=c(0,xLim), ylim=c(0,yLim), xlab="", ylab="", xaxt="n", yaxt="n", bty="n")
par(new=T)
plot((PReadStats[,"Mean"]/xScf), (PReadStats[,"SEQ"]/yScf), pch=16, col="black", bg="black", lwd=2, cex=2.0, xlim=c(0,xLim), ylim=c(0,yLim), xlab="", ylab="", xaxt="n", yaxt="n", bty="n")
par(new=T)
plot((PReadStats[,"Median"]/xScf), (PReadStats[,"SEQ"]/yScf), pch=21, col="red4", bg="white", lwd=2, cex=2.0, xlim=c(0,xLim), ylim=c(0,yLim), xlab="", ylab="", xaxt="n", yaxt="n", bty="n")

axis(1, pos=0, at=seq(0,xLim,((xLim/stp)*2)), labels=paste(seq(0,xLim,((xLim/stp)*2)), "kb", sep=""))
axis(2, pos=0, at=seq(0,yLim,((yLim/stp)*2)), labels=paste(seq(0,yLim,((yLim/stp)*2)), "Gb", sep=""))
axis(3, pos=yLim, at=c(0,xLim), labels=c("",""))
axis(4, pos=xLim, at=c(0,yLim), labels=c("",""))

mtext("Polymerase read length", 1, line=1)
mtext("Sequence yield", 2, line=1)

dev.off()
#-



#-	3)	SMRT cell processed output plot
ppRow<-800
ppCol<-800

pRows<-1
pCols<-1

covCols<-c(colorRampPalette(brewer.pal(8,"RdYlGn")[1:4])(10),colorRampPalette(brewer.pal(8,"RdYlGn")[5:8])(10))

xLim<-40
yLim<-10
stp<-20
xScf<-1000
yScf<-1000000000


png(paste(SPEC, "SMRT_cell.processed_output.png", sep="."), width=(pCols*ppCol), height=(pRows*ppRow))

plot(NULL, xlim=c(0,xLim), ylim=c(0,yLim), xlab="", ylab="", xaxt="n", yaxt="n", bty="n", main="SMRT cell processed output analysis")

for (i in 1:stp) {
	tCol<-col2rgb(covCols[i])
	xf<-xLim/stp
	rect(((i-1)*xf), 0, (i*xf), yLim, col=rgb(tCol[1], tCol[2], tCol[3], 128, maxColorValue=255), border=NA)
}

for (i in 1:stp) {
	tCol<-col2rgb(covCols[i])
	yf<-yLim/stp
	rect(0, ((i-1)*yf), xLim, (i*yf), col=rgb(tCol[1], tCol[2], tCol[3], 128, maxColorValue=255), border=NA)
}


for (i in 11:stp) {
	tCol<-col2rgb(covCols[i])
	xf<-xLim/stp
	yf<-yLim/stp
	rect(((i-1)*xf), (10*yf), (i*xf), (16*yf), col=rgb(tCol[1], tCol[2], tCol[3], 128, maxColorValue=255), border=NA)
}

for (i in 11:16) {
	tCol<-col2rgb(covCols[i])
	xf<-xLim/stp
	yf<-yLim/stp
	rect((10*xf), ((i-1)*yf), xLim, (i*yf), col=rgb(tCol[1], tCol[2], tCol[3], 128, maxColorValue=255), border=NA)
}


for (i in 0:stp) {
	xf<-xLim/stp
	yf<-yLim/stp
	
	lines(c(0,xLim), c((i*yf),(i*yf)), col="black", lwd=1, lty=3)
	lines(c((i*xf),(i*xf)), c(0,yLim), col="black", lwd=1, lty=3)
}

lines(c(0,xLim), c((yLim/2),(yLim/2)), col="black", lwd=1, lty=1)
lines(c((xLim/2),(xLim/2)), c(0,yLim), col="black", lwd=1, lty=1)

rect((xLim/2), (yLim/2), xLim, ((yLim/stp)*16), col=NA, border="black", lwd=1, lty=1)


for (i in SMRTcells) {
	tY<-(SReadStats[i,"SEQ"]/yScf)
	tXl<-(SReadStats[i,"Median"]/xScf)
	tXr<-(SReadStats[i,"N50"]/xScf)
	
	lines(c(tXl,tXr), c(tY,tY), col="black", lwd=1, lty=1)
}

par(new=T)
plot((SReadStats[,"N50"]/xScf), (SReadStats[,"SEQ"]/yScf), pch=21, col="black", bg="white", lwd=2, cex=2.0, xlim=c(0,xLim), ylim=c(0,yLim), xlab="", ylab="", xaxt="n", yaxt="n", bty="n")
par(new=T)
plot((SReadStats[,"Mean"]/xScf), (SReadStats[,"SEQ"]/yScf), pch=16, col="black", bg="black", lwd=2, cex=2.0, xlim=c(0,xLim), ylim=c(0,yLim), xlab="", ylab="", xaxt="n", yaxt="n", bty="n")
par(new=T)
plot((SReadStats[,"Median"]/xScf), (SReadStats[,"SEQ"]/yScf), pch=21, col="red4", bg="white", lwd=2, cex=2.0, xlim=c(0,xLim), ylim=c(0,yLim), xlab="", ylab="", xaxt="n", yaxt="n", bty="n")

axis(1, pos=0, at=seq(0,xLim,((xLim/stp)*2)), labels=paste(seq(0,xLim,((xLim/stp)*2)), "kb", sep=""))
axis(2, pos=0, at=seq(0,yLim,((yLim/stp)*2)), labels=paste(seq(0,yLim,((yLim/stp)*2)), "Gb", sep=""))
axis(3, pos=yLim, at=c(0,xLim), labels=c("",""))
axis(4, pos=xLim, at=c(0,yLim), labels=c("",""))

mtext("Longest subread", 1, line=1)
mtext("Sequence yield", 2, line=1)

dev.off()
#-



#-	4)	Sequencing efficiency plot
ppRow<-800
ppCol<-800

pRows<-1
pCols<-1


png(paste(SPEC, "SMRT_cell.efficiency.png", sep="."), width=(pCols*ppCol), height=(pRows*ppRow))

plot(NULL, xlim=c(0,1), ylim=c(0,1), xlab="", ylab="", xaxt="n", yaxt="n", bty="n", main="Sequencing efficiency")

for (i in seq(0.1,0.5,0.1)) {
	tCol<-col2rgb("red4")
	rect((i-0.1), 0, i, 1, col=rgb(tCol[1], tCol[2], tCol[3], (128-((i-0.1)*10*13)), maxColorValue=255), border=NA)
}

for (i in rev(seq(0.6,1,0.1))) {
	tCol<-col2rgb("red4")
	rect(0, (i-0.1), 1, i, col=rgb(tCol[1], tCol[2], tCol[3], (128-((1-i)*10*13)), maxColorValue=255), border=NA)
}

for (i in seq(0,1,0.1)) {
	lines(c(0,1), c(i,i), col="grey40", lwd=1, lty=3)
	lines(c(i,i), c(0,1), col="grey40", lwd=1, lty=3)
}

lines(c(0,1), c(0.5,0.5), col="black", lwd=1, lty=1)
lines(c(0.5,0.5), c(0,1), col="black", lwd=1, lty=1)


par(new=T)
plot(PReadStats[,"PSR"], PReadStats[,"ZOR"], pch=16, col="black", cex=2, xlim=c(0,1), ylim=c(0,1), xlab="", ylab="", xaxt="n", yaxt="n", bty="n")

axis(1, pos=0, at=seq(0,1,0.1), labels=seq(0,1,0.1))
axis(2, pos=0, at=seq(0,1,0.1), labels=seq(0,1,0.1))
axis(3, pos=1, at=c(0,1), labels=c("",""))
axis(4, pos=1, at=c(0,1), labels=c("",""))

mtext("Polymerase read to Subread Ratio (PSR)", 1, line=1)
mtext("ZMW Occupancy Ratio (ZOR)", 2, line=1)

dev.off()
#-



#-	5)	Sequencing run yield & efficiency
ppRow<-300
ppCol<-300

pRows<-ceiling(length(SMRTcells)/6)
pCols<-length(SMRTcells)

if(pCols>6) { pCols<-6 }

lCol<-"white"
sMax<-1.6e10
sStp<-1e9


png(paste(SPEC, "seq_run.yield_and_efficiency.png", sep="."), width=(pCols*ppCol), height=(pRows*ppRow))

par(mfrow=c(pRows,pCols))

for (i in SMRTcells) {
	barplot(c(sum(as.numeric(PacBio.stats[[i]][["LQ"]]["SEQ","ZR"])), sum(as.numeric(PacBio.stats[[i]][["MQ"]]["SEQ","ZR"])), sum(as.numeric(PacBio.stats[[i]][["HQ"]]["SEQ","ZR"])), sum(as.numeric(PacBio.stats[[i]][["HQ"]]["SEQ","PR"])), sum(as.numeric(PacBio.stats[[i]][["HQ"]]["SEQ","SR"]))), beside=T, names.arg=c("LQ","MQ","HQ","HQS","LSR"), col=c("black","black","black","red4","green4"), border=NA, ylim=c(0,sMax), ylab="Sequence per category", main=i)
	for (i in seq(0,sMax,sStp)) { lines(c(0,(5+4)), c(i,i), lwd=1, lty=3, col=lCol) }
	tCol<-col2rgb("red4")
	rect(0, 5e9, (5+4), 8e9, col=rgb(tCol[1], tCol[2], tCol[3], 64, maxColorValue=255), border=NA)
}

dev.off()
#-



#-	6)	Estimated library size distribution
ppRow<-300
ppCol<-480

pRows<-ceiling(length(SMRTcells)/4)
pCols<-length(SMRTcells)

if(pCols>4) { pCols<-4 }

maxRLength<-ceiling(max(PacBio.max[,"LEN"]) / 10000) * 10000
yMax<-0

for (i in SMRTcells) { yMax<-max(yMax, max(hist(PacBio.other[[i]][["HQ"]][["lFlg"]], breaks=seq(0,maxRLength,100), plot=F)$density)) }


png(paste(SPEC, "estimated_lib_size_distribution.png", sep="."), width=(pCols*ppCol), height=(pRows*ppRow))

par(mfrow=c(pRows,pCols))

for (i in SMRTcells) {
	hist(PacBio.other[[i]][["HQ"]][["lFlg"]], breaks=seq(0,maxRLength,100), freq=F, col="green4", border=NA, xlim=c(0,60000), ylim=c(0,yMax), xlab="", main=i)
	par(new=T)
	tmp<-density(PacBio.other[[i]][["HQ"]][["lFlg"]])
	plot(tmp, xlim=c(0,60000), lwd=2, ylim=c(0,yMax), ylab="", xaxt="n", yaxt="n", bty="n", main="")
}

dev.off()
#-



#-	7)	Estimated library size distribution (full data)
ppRow<-300
ppCol<-480

pRows<-1
pCols<-2

lFlg<-NULL
aCnt<-NULL

for (i in SMRTcells) {
	lFlg<-c(lFlg, PacBio.other[[i]][["HQ"]][["lFlg"]])
	aCnt<-c(aCnt, PacBio.other[[i]][["HQ"]][["aCnt"]])
}

maxRLength<-ceiling(max(PacBio.max[,"LEN"]) / 10000) * 10000
yMax<-max(max(hist(lFlg, breaks=seq(0,maxRLength,100), plot=F)$density), max(hist(aCnt, breaks=seq(0,maxRLength,100), plot=F)$density))


png(paste(SPEC, "estimated_lib_size_distribution.full_data.png", sep="."), width=(pCols*ppCol), height=(pRows*ppRow))

par(mfrow=c(pRows,pCols))

hist(lFlg, breaks=seq(0,maxRLength,100), freq=F, col="green4", border=NA, xlim=c(0,60000), ylim=c(0,yMax), xlab="", main="Adapter flanked")
par(new=T)
tmp<-density(lFlg)
plot(tmp, xlim=c(0,60000), lwd=2, ylim=c(0,yMax), ylab="", xaxt="n", yaxt="n", bty="n", main="")

hist(aCnt, breaks=seq(0,maxRLength,100), freq=F, col="green4", border=NA, xlim=c(0,60000), ylim=c(0,yMax), xlab="", main="Single adapter")
par(new=T)
tmp<-density(aCnt)
plot(tmp, xlim=c(0,60000), lwd=2, ylim=c(0,yMax), ylab="", xaxt="n", yaxt="n", bty="n", main="")

dev.off()
#-

